### ISSUE TITLE
console.log 章节第二张图重复了第一张图

### ISSUE THREAD

**Issue by islishude** [zhansingsong/js-leakage-patterns#1]
![image](https://user-images.githubusercontent.com/24730006/33481177-51362b5a-d6ce-11e7-95fa-c8f1ecfa900b.png)

这里这张图重复了第一张图，我看了文章目录和 reademe，确实是这样，第二张图地址应该是 `![](./console_2.png)`

**Comment by zhansingsong** [comment]
谢谢，已修正
