### ISSUE TITLE
“DOM泄露”中的<小试牛刀>的代码注释有误

### ISSUE THREAD

**Issue by Silencewanghui** [zhansingsong/js-leakage-patterns#2]
“DOM泄露”中的<小试牛刀>的代码注释有误

> 还存在变量refB对#refB的间接引用

应该是**refB对#refA的间接引用**

**Comment by zhansingsong** [comment]
@Silencewanghui  谢谢！已更正。
附图验证一下：
![](https://raw.githubusercontent.com/zhansingsong/js-leakage-patterns/master/images/fixbug.png)
