### ISSUE TITLE
作者，你真的自己测试了吗！！！

### ISSUE THREAD

**Issue by chenjianfang** [zhansingsong/js-leakage-patterns#4]
我在谷歌浏览器测试了文中的全局属性、console.log、闭包、DOM泄露。只有console.log会对造成内存泄露，其他三种都会被引擎自动GC，用不用文中的方法都没影响！

**Comment by zhansingsong** [comment]
@chenjianfang  老铁，首先感谢你的阅读和回复。作者我肯定测试过的，不然demo怎么出来的，自己YY的吗？我不知道你怎么测试的，也许操作上存在的问题，或新版Chrome做了优化。不过自己升级了Chrome浏览器测试了一下，是没有问题的。还有demos文件中，有些demo是优化过的，不是有问题的demo，你用优化过的demo肯定是发现不了问题的。后续有时间我还是把dome规整一下，避免类似的问题。

Mac: 
Google Chrome 已是最新版本
版本 63.0.3239.108（正式版本） （64 位）
